apiVersion: v1
kind: ConfigMap
metadata:
  name: gardener-config
  namespace: default
data:  # TODO - use kubectl to create the contents --from-file
  config.yaml: |
    project: mlab-testing
    commit: foobar
    release: private # Consider adding the branch-name
    tracker:
      timeout: 5h
    monitor:
      polling_interval: 5m
    sources:
    - bucket: archive-measurement-lab
      datatype: tcpinfo
      archive_path: ndt/tcpinfo
      filter: .*T??:??:00.*Z
      start: 2019-08-01
      target: ndt.tcpinfo
    - bucket: archive-measurement-lab
      datatype: tcpinfo
      archive_path: ndt/ndt5
      filter: .*T??:??:00.*Z
      start: 2019-08-01
      target: ndt.ndt5
